### ISSUE TITLE
"Work in progress" README section should state if it can connect to browser's WebRTC or not.

### ISSUE THREAD

**Issue by vi** [simmons/webrtc-sctp#1]
Can it actually connect to `RTCPeerConnection` in Chromium or Firefox?

Either way, the answer should be the first phrase in README.

**Comment by Skarlett** [comment]
This should be closed already.

**Comment by edin-m** [comment]
Is this project alive?

**Comment by simmons** [comment]
Hi, @edin-m --

Development has been on hiatus lately due to:
1. I've been pressed for time due to external obligations in recent months, and
2. The Rust async/await features, futures, and tokio have been evolving rapidly, and I've been hesitant to put in the work to migrate the code base to newer versions until some semblance of stability has been reached.

However, I'm highly motivated to see this project become a reality, and it looks like async/await will be stabilized in [Rust 1.38](http://smallcultfollowing.com/babysteps/blog/2019/07/08/async-await-status-report-2/), so hopefully things will start moving again really soon.

Regarding the issue topic -- I've demonstrated this code interoperating with Chrome and Firefox, but critical protocol features required to be a good network citizen are missing, so the first phrase in the README is exactly as it should be -- a warning not to use this code in its present state.
